vcs-python/libvcs

- doc/api.rst
- libvcs/base.py
- libvcs/git.py
- libvcs/hg.py
- libvcs/util.py
- tests/test_git.py
- tests/test_hg.py
This removes buffered output from repos completely.
This gets rid of a lot of distractions and opens the way for thread
safety / easier development / leaner codebase for other developers.
See also: #6
> Remove all buffering

- libvcs/git.py
This commit fixes error like this one:
```
Traceback (most recent call last):
File "./extensions-index-checkout.py", line 150, in <module>
duration, result = timecall(repo.update_repo)()
File "./extensions-index-checkout.py", line 53, in wrapper
result = method(*args, **kwargs)
File "/home/jcfr/Projects/sandbox/libvcs/libvcs/git.py", line 198, in update_repo
self.debug("tag_sha: %s" % tag_sha)
UnboundLocalError: local variable 'tag_sha' referenced before assignment
```
> ylibvcs.git: Fix unbound local variable 'tag_sha' error

- tests/test_git.py
For https://github.com/vcs-python/vcspull/pull/362
> Remotes: Part 1 (tests)

- .github/workflows/docs.yml
- .github/workflows/tests.yml
- CHANGES
As of yesterday, `@actions/setup-python@v3` supports this via v3.1.0: [Release](https://github.com/actions/setup-python/releases/tag/v3.1.0), [Tag](https://github.com/actions/setup-python/tree/v3.1.0), https://github.com/actions/setup-python/pull/281
```yaml
steps:
- uses: actions/checkout@v3
- name: Install poetry
run: pipx install poetry
- uses: actions/setup-python@v3
with:
python-version: '3.9'
cache: 'poetry'
- run: poetry install
- run: poetry run pytest
```
See also: https://github.com/python-poetry/poetry/discussions/4205
> ci(tests): Use poetry cache action

- CHANGES
- README.md
- libvcs/conftest.py
- libvcs/shortcuts.py
- libvcs/states/base.py
- libvcs/states/git.py
- libvcs/states/hg.py
- libvcs/states/svn.py
- tests/states/test_base.py
- tests/states/test_git.py
- tests/states/test_hg.py
- tests/states/test_svn.py
- tests/test_shortcuts.py
`repo_dir` param is renamed to `dir`:
Before: `GitRepo(url='...', repo_dir='...')`
After: `GitRepo(url='...', dir='...')`
> refactor!: Rename `repo_dir` to `dir`

- CHANGES
- libvcs/cmd/git.py
`git reset`, `git checkout`, `git status`
> More git commands

- CHANGES
- libvcs/cmd/git.py
> `cmd.git`: Command fixes, add `git config`

- CHANGES
- libvcs/_internal/run.py
- libvcs/cmd/git.py
- libvcs/cmd/hg.py
- libvcs/cmd/svn.py
As part of us migrating to `SubprocessCommand` #340 , make existing `run()` directly compatible with `subprocess.Popen`
> chore(run): Pass through to `subprocess.Popen`

- CHANGES
- libvcs/projects/base.py
- libvcs/projects/git.py
- libvcs/projects/svn.py
- libvcs/shortcuts.py
To make passing as a configuration file (#315 and https://github.com/vcs-python/vcspull/pull/362) easier, deprecate positional arguments.
Deprecated in >=0.13:
```python
GitProject('https://github.com/vcs-python/libvcs.git')
```
New style in >=0.13:
```python
GitProject(url='https://github.com/vcs-python/libvcs.git')
```
See also:
- PEP 570: https://peps.python.org/pep-0570/
- https://peps.python.org/pep-0570/#:~:text=def%20kwd_only_arg*%2C%20arg)(%3A)
> refactor!(projects): Make arguments kw-only

- libvcs/cmd/git.py
- libvcs/cmd/hg.py
- libvcs/cmd/svn.py
Since libvcs is <1.0, lets clamp down on positional arguments
until things are stable. Positional arguments are great, when
there's a high degree of confidence in the first arg.
We're not 100% on these as we're stubbing out endpoints rapidly at this
juncture.
See also: https://docs.python.org/3.8/whatsnew/3.8.html#positional-only-parameters
> refactor!(cmd): Keyword-only params

- .github/workflows/tests.yml
- CHANGES
- docs/conf.py
- docs/contributing/workflow.md
- libvcs/_internal/run.py
- libvcs/_internal/subprocess.py
- libvcs/cmd/git.py
- libvcs/cmd/svn.py
- libvcs/conftest.py
- libvcs/projects/base.py
- libvcs/projects/git.py
- tests/_internal/subprocess/test_SubprocessCommand.py
- tests/projects/test_base.py
- tests/projects/test_git.py
- tests/projects/test_svn.py
> chore: mypy and additional type annotations

- CHANGES
- libvcs/projects/git.py
See also:
- https://github.com/python/cpython/commit/ead169d3114ed0f1041b5b59ca20293449608c50
- https://bugs.python.org/issue8657 or
https://github.com/python/cpython/issues/52903#issuecomment-1093501859
> chore(git): Remove `uses_netloc` for `git+ssh`, already in cpython

- CHANGES
- libvcs/projects/git.py
Deprecated since pip 21.0, insecure
See also:
- https://github.com/pypa/pip/blob/22.1.2/NEWS.rst#deprecations-and-removals-16
- https://github.com/pypa/pip/commit/eeeecbe856a6156bbab1eb319fd32849e8b11da9
- https://github.com/pypa/pip/pull/7543
> chore!(git): Remove insecure `git+git` support

- CHANGES
- libvcs/projects/git.py
See also:
- #378 (removes 'git+ssh')
- https://github.com/python/cpython/commit/ead169d3114ed0f1041b5b59ca20293449608c50
- https://bugs.python.org/issue8657 or
https://github.com/python/cpython/issues/52903#issuecomment-1093501859
> chore(git): Remove another already supported netloc scheme ('git')

- CHANGES
- docs/parse/git.md
- libvcs/parse/base.py
- libvcs/parse/git.py
- libvcs/parse/hg.py
- libvcs/parse/svn.py
- tests/parse/test_git.py
- tests/parse/test_hg.py
- tests/parse/test_svn.py
Parser:
- Fix port detection in svn and hg
- Add port detection to git
- Use `rev` to parse branch, tag, and references with git
- `GitBaseURL` and `GitPipURL`
> Parser: Improvements, tests

- CHANGES
- libvcs/parse/base.py
- libvcs/parse/git.py
- libvcs/parse/hg.py
- libvcs/parse/svn.py
- tests/parse/test_git.py
- tests/parse/test_hg.py
- tests/parse/test_svn.py
Parser:
- Git scp-style URLs: Fix detection detect of scp style URLs with `.git` prefixes
- Fix critical bug where `matchers` were being applied as variable not annotations
- Fix `pattern_defaults`
- Base tests: Rename `Location` to `URL`
- Tests and modules: Rename `_location` to `_url`
> Parser: Support explicit matchers, critical bug fixes

- CHANGES
- src/libvcs/_internal/query_list.py
- tests/_internal/test_query_list.py
This came up in https://github.com/tmux-python/libtmux/pull/426 when querying lists of dataclass objects
> QueryList: Better object handling

- CHANGES
- README.md
- src/libvcs/url/base.py
- src/libvcs/url/git.py
- src/libvcs/url/hg.py
- src/libvcs/url/svn.py
- tests/url/test_git.py
- tests/url/test_hg.py
- tests/url/test_svn.py
- refactor(url): 
- `Matcher` -> `Rule`, `MatcherRegistry` -> `Rules`
- `matches` -> `rule_map`
- `default_patterns` -> `patterns`
- `MATCHERS` -> `RULES`
> URLs: Renaming

- CHANGES
- docs/url/index.md
- docs/url/registry.md
- src/libvcs/_internal/module_loading.py
- src/libvcs/_internal/shortcuts.py
- src/libvcs/url/registry.py
- tests/url/test_registry.py
Required by https://github.com/vcs-python/vcspull/pull/373
and i dont have time to do this until the weekend
Todo:
> vcs-registry: All vcspull compatible URLs must have URLs detected

- src/libvcs/pytest_plugin.py
In re: https://github.com/vcs-python/libvcs/pull/425#issuecomment-1257308374
This would allow passing `--bare` to `create_git_remote_repo(init_kwargs=['--bare'])`
> feat(pytest_plugin): Allow passing init flags to repo fixtures

- CHANGES
- src/libvcs/sync/git.py
- tests/sync/test_git.py
Second attempt at fixing #395
Alternative to #422
I'm going to see if I can add tests in case there are conflicts.
> fix(git): Fix update_repo when there are untracked files (Take 2)

- CHANGES
- docs/url/registry.md
- src/libvcs/url/base.py
- src/libvcs/url/git.py
- tests/url/test_git.py
This example found that the `defaults` will get overwritten by a URL running through all matchers. It should only use the defaults of the one ultimately being picked
And how do we pick the "best" one?
> Registry examples
